CREATE DATABASE proyecto;

USE proyecto;
CREATE	TABLE	`USUARIS`	(
		`USUARI_ConsInte__b`	int(10)	NOT	NULL	AUTO_INCREMENT,
		`USUARI_Codigo____b`	varchar(50) CHARACTER SET utf8	DEFAULT	NULL,
		`USUARI_Clave_____b`	varchar(253) CHARACTER SET	utf8	NOT	NULL,
		`USUARI_Nombre____b`	varchar(253) CHARACTER SET	utf8	NOT	NULL,
		`USUARI_Cargo_____b`	varchar(253) CHARACTER SET	utf8	DEFAULT	NULL,
		`USUARI_ConsInte__PERUSU_b`	int(10)	DEFAULT	NULL,
		`USUARI_InMoCoPa__b`	smallint(5)	NOT	NULL	DEFAULT	'0',
		`USUARI_InPeToGu__b`	smallint(5)	NOT	NULL	DEFAULT	'0',
		`USUARI_IndPerCap_b`	smallint(5)	NOT	NULL	DEFAULT	'0',
		`USUARI_IndPerRep_b`	smallint(5)	NOT	NULL	DEFAULT	'0',
		`USUARI_InPeMoPo__b`	smallint(5)	NOT	NULL	DEFAULT	'0',
		`USUARI_Identific_b`	varchar(50)	DEFAULT	NULL,
		`USUARI_UsuaTele__b`	varchar(50)	DEFAULT	NULL,
		`USUARI_ClavTele__b`	varchar(50)	DEFAULT	NULL,
		`USUARI_ConsInte__TURNOS_b`	int(10)	DEFAULT	NULL,
		`USUARI_ClaSalLla_b`	varchar(50)	DEFAULT	NULL,
		`USUARI_LlavExte__b`	varchar(50)	CHARACTER SET	utf8	DEFAULT	NULL,
		`USUARI_IndiActi__b`	smallint(5)	DEFAULT	'-1',
		`USUARI_NaciAnno__b`	int(10)	DEFAULT	NULL,
		`USUARI_NaciMes___b`	int(10)	DEFAULT	NULL,
		`USUARI_NaciDia___b`	int(10)	DEFAULT	NULL,
		`USUARI_SegConVen_b`	smallint(5)	DEFAULT	'0',
		`USUARI_SegDiaVen_b`	int(10)	DEFAULT	'90',
		`USUARI_LonMinCon_b`	int(10)	DEFAULT	'4',
		`USUARI_RepConDia_b`	int(10)	DEFAULT	'180',
		`USUARI_SegFecCon_b`	datetime	DEFAULT	NULL,
		`USUARI_Bloqueado_b`	smallint(5)	DEFAULT	'0',
		`USUARI_FechCrea__b`	datetime	DEFAULT	NULL,
		`USUARI_UsuaCrea__b`	varchar(253)	DEFAULT	NULL,
        `USUARI_ConsInte__PROYEC_b`	int(11)	DEFAULT	NULL,
		`USUARI_Foto______b`	varchar(255)	DEFAULT	NULL,
		`USUARI_UsuaCBX___b`	int(11)	DEFAULT	NULL,
		`USUARI_ConsInte__USUPER_b`	int(10)	DEFAULT	NULL,
		`USUARI_PerCamCam_b`	smallint(5)	NOT	NULL	DEFAULT	'-1',
		`USUARI_Correo___b`		varchar(255)	DEFAULT	NULL,
		`USUARI_passCorreo_b`	varchar(255)	DEFAULT	NULL,
		`USUARI_HorIniLun_b`	time	DEFAULT	NULL,
        `USUARI_HorFinLun_b`	time	DEFAULT	NULL,
		`USUARI_HorIniMar_b`	time	DEFAULT	NULL,
		`USUARI_HorFinMar_b`	time	DEFAULT	NULL,
		`USUARI_HorIniMie_b`	time	DEFAULT	NULL,
		`USUARI_HorFinMie_b`	time	DEFAULT	NULL,
		`USUARI_HorIniJue_b`	time	DEFAULT	NULL,
		`USUARI_HorFinJue_b`	time	DEFAULT	NULL,
		`USUARI_HorIniVie_b`	time	DEFAULT	NULL,
		`USUARI_HorFinVie_b`	time	DEFAULT	NULL,
		`USUARI_HorIniSab_b`	time	DEFAULT	NULL,
		`USUARI_HorFinSab_b`	time	DEFAULT	NULL,
		`USUARI_HorIniDom_b`	time	DEFAULT	NULL,
		`USUARI_HorFinDom_b`	time	DEFAULT	NULL,
		`USUARI_HorIniFes_b` 	time	DEFAULT	NULL,
		`USUARI_HorFinFes_b`	time	DEFAULT	NULL,
		`updated_at`	datetime	DEFAULT	NULL,
		PRIMARY KEY	(`USUARI_ConsInte__b`),
		UNIQUE	KEY	`USUARI_ConsInte__b_UNIQUE`	(`USUARI_ConsInte__b`),
		KEY	`fk_PROYEC_USUARI_idx`	(`USUARI_ConsInte__PROYEC_b`)
)	ENGINE=InnoDB AUTO_INCREMENT=1	DEFAULT	CHARSET=latin1;

USE proyecto;
CREATE	TABLE	`users`	(
    	 `USUARI_ConsInte__b` int(10) NOT NULL AUTO_INCREMENT,
         `name` varchar(253) CHARACTER SET utf8 NOT NULL,
         `email` varchar(253) NOT NULL,
         `email_verified_at` varchar(253) DEFAULT NULL,
         `password` varchar(253) NOT NULL,
         `rememberToken` varchar(253) DEFAULT NULL,
         `timestamps` datetime DEFAULT NULL,
		 `updated_at` datetime DEFAULT	NULL,
		 `created_at` varchar(253) DEFAULT NULL,
		PRIMARY KEY	(`USUARI_ConsInte__b`),
		UNIQUE	KEY	`USUARI_ConsInte__b_UNIQUE`	(`USUARI_ConsInte__b`)
)	ENGINE=InnoDB AUTO_INCREMENT=1	DEFAULT	CHARSET=latin1;